# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9jcm4ah91-2eixuMMXO74PzRWNgU9qM
"""

import re

chat1= "Hi, my order ORD-98231 hasn’t arrived. You can reach me at 9876543210 or rahul.mehta@gmail.com"
chat2= "Please book a technician for order SRV-44512, contact +91-9123456789, email tech.user@outlook.com"
chat3= "I can’t log in to my account (user123@email.com), ticket TCK-77890, phone 9012345678."
chat4= "Any update on ORDER-55678? My email is ananya.singh@company.in, phone +91 9988776655."

pattern_for_number= '\W+\d{2} \d{10}|\W+\d{2}\-\d{10}|\d{10}'
mat_num= re.findall(pattern_for_number, chat3)
mat_num

pattern_for_email= '[a-z0-9A-Z_.-]*@[a-z0-9A-z]*\.[a-z]*'
ema_mat= re.findall(pattern_for_email, chat4)
ema_mat

pattern_for_order= '[a-zA-Z]*-[^\d]*(\d*)'
ord_mat= re.findall(pattern_for_order, chat4)
ord_mat

text= '''
Khan began his career with appearances in several television series in the late 1980s and made his Hindi film debut in 1992 with the musical romance Deewana. He was initially recognised for playing villainous roles in the films Baazigar (1993) and Darr (1993). Khan established himself by starring in a series of top-grossing romantic films, including Dilwale Dulhania Le Jayenge (1995), Dil To Pagal Hai (1997), Kuch Kuch Hota Hai (1998), Mohabbatein (2000), Kabhi Khushi Kabhie Gham (2001), Kal Ho Naa Ho (2003), Veer-Zaara (2004), and Kabhi Alvida Naa Kehna (2006). He earned critical acclaim for his portrayal of an alcoholic in the period romantic drama Devdas (2002), a NASA scientist in the social drama Swades (2004), a hockey coach in the sports drama Chak De! India (2007), and a man with Asperger syndrome in the drama My Name Is Khan (2010). Further commercial successes came with the romances Om Shanti Om (2007) and Rab Ne Bana Di Jodi (2008), and with his expansion to comedies in Chennai Express (2013) and Happy New Year (2014). Following a brief setback and hiatus, Khan made a career comeback with the 2023 action thrillers Pathaan and Jawan, both of which rank among the highest-grossing Indian films. For Jawan, he received the National Film Award for Best Actor in a Leading Role.
'''

def info_Generator(text:str):
  pat_years= '\(\d*\)'